# syntax=docker.io/docker/dockerfile:1.7-labs
FROM node:22.14.0-bookworm
WORKDIR /src
COPY --exclude=node_modules --exclude=Dockerfile.testing --exclude=docker-compose.testing.yml . .
RUN npm install

# !! KEEP IN SYNC WITH playwright IN PACKAGE.JSON
RUN npx playwright@1.51.1 install --with-deps
